spring:
  profiles:
    active: db
  application:
    name: PlanMateBackend
  datasource:
    url: jdbc:mysql://localhost:3307/seniorprojectdb?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop

firebase:
  credentials:
    path: src/main/resources/firebase-service-account.json

logging:
  level:
    org:
      springframework:
        security: DEBUG